os: linux
dist: xenial
language: perl
perl:
  - "5.26"

before_install:
  - if [ -z ${TRAVIS_TAG} ] || [ ${TRAVIS_TAG} == *-* ]; then export VERSION=latest; else export VERSION=${TRAVIS_TAG}; fi
  - echo ${TRAVIS_TAG}
  - echo ${VERSION}

install:
  -

script:
  - sed 's/"latest"/"${VERSION}"/' ercole-agent > /tmp/ercole-agent
  - cp /tmp/ercole-agent ercole-agent
  - tar -C . -cvzf /tmp/ercole-agent-hpux-${VERSION}.tar.gz .